import { Transaction } from './index';

export const CATEGORIES = [
  'Groceries',
  'Transportation',
  'Entertainment',
  'Utilities',
  'Healthcare',
  'Salary',
  'Freelance',
  'Other',
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    date: '2024-03-28',
    amount: 5000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '2',
    date: '2024-03-27',
    amount: 1200,
    category: 'Utilities',
    type: 'expense',
    description: 'Electricity and water bill',
  },
  {
    id: '3',
    date: '2024-03-26',
    amount: 450,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly groceries',
  },
  {
    id: '4',
    date: '2024-03-25',
    amount: 75,
    category: 'Entertainment',
    type: 'expense',
    description: 'Movie tickets',
  },
  {
    id: '5',
    date: '2024-03-24',
    amount: 200,
    category: 'Transportation',
    type: 'expense',
    description: 'Gas and maintenance',
  },
  {
    id: '6',
    date: '2024-03-23',
    amount: 3000,
    category: 'Freelance',
    type: 'income',
    description: 'Project completion payment',
  },
  {
    id: '7',
    date: '2024-03-22',
    amount: 500,
    category: 'Groceries',
    type: 'expense',
    description: 'Groceries shopping',
  },
  {
    id: '8',
    date: '2024-03-21',
    amount: 150,
    category: 'Healthcare',
    type: 'expense',
    description: 'Doctor appointment',
  },
  {
    id: '9',
    date: '2024-03-20',
    amount: 100,
    category: 'Entertainment',
    type: 'expense',
    description: 'Dinner out',
  },
  {
    id: '10',
    date: '2024-03-19',
    amount: 250,
    category: 'Transportation',
    type: 'expense',
    description: 'Uber rides',
  },
  {
    id: '11',
    date: '2024-03-18',
    amount: 800,
    category: 'Utilities',
    type: 'expense',
    description: 'Internet and phone',
  },
  {
    id: '12',
    date: '2024-03-17',
    amount: 1000,
    category: 'Healthcare',
    type: 'expense',
    description: 'Medical insurance',
  },
  {
    id: '13',
    date: '2024-03-16',
    amount: 350,
    category: 'Groceries',
    type: 'expense',
    description: 'Weekly groceries',
  },
  {
    id: '14',
    date: '2024-03-15',
    amount: 200,
    category: 'Entertainment',
    type: 'expense',
    description: 'Concert tickets',
  },
  {
    id: '15',
    date: '2024-03-14',
    amount: 5000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '16',
    date: '2024-02-28',
    amount: 5000,
    category: 'Salary',
    type: 'income',
    description: 'Monthly salary',
  },
  {
    id: '17',
    date: '2024-02-27',
    amount: 2000,
    category: 'Freelance',
    type: 'income',
    description: 'Freelance project',
  },
  {
    id: '18',
    date: '2024-02-26',
    amount: 1500,
    category: 'Utilities',
    type: 'expense',
    description: 'Utility bills',
  },
  {
    id: '19',
    date: '2024-02-25',
    amount: 600,
    category: 'Groceries',
    type: 'expense',
    description: 'Groceries',
  },
  {
    id: '20',
    date: '2024-02-24',
    amount: 300,
    category: 'Entertainment',
    type: 'expense',
    description: 'Weekend outing',
  },
];
